// By and copyright Julian D. A. Wiseman of www.jdawiseman.com, April 2025
// Released under GNU General Public License, Version 3, https://www.gnu.org/licenses/gpl-3.0.txt
// main.c, in PenroseC

#include "penrose.h"

// Change to match your directory structure, and location of applications.
static char const filePath_staticConst[] = "/Users/JDAW/Documents/outputPenrose/";

#define AnyPostProcessing false

// Location and name of application should match your machine's arrangement. Or can become empty do-nothing.
void execute_SVG_PostProcessing(
	const Tiling * const tlngP,
	const unsigned long int numLinesThisFile,
	const unsigned long long int numCharsThisFile,
	const char * const fileName,
	ExportFormat const ef
)
{
	extern char scratchString[];
	if( AnyPostProcessing )
	{
		if( ef == SVG_arcs  ||  numCharsThisFile < 10737418240 )  // 10 MiB. Limit very different for arcs and rhombi. https://issues.chromium.org/issues/390969197
		{
			// Change next line to invoke your preferred browser.
			sprintf(scratchString, "open -a '/Applications/Google Chrome.app' 'file://%s'", fileName);
			system(scratchString);  // In general, system() can be a serious security risk. If concerned, delete.
		}  // Not too big
	}  // AnyPostProcessing
}  // execute_SVG_PostProcessing()

// Location and name of application should match your machine's arrangement. Or can become empty do-nothing.
void execute_PostScript_PostProcessing(
	const Tiling * const tlngP,
	const unsigned long int numLinesThisFile,
	const unsigned long long int numCharsThisFile,
	const char * const fileName,
	ExportFormat const ef
)
{
	extern char scratchString[];
	if( AnyPostProcessing )
	{
		// Change next line to invoke your preferred PS-to-PDF application, likely either Distiller or GhostScript.
		sprintf(scratchString, "open -a '/Applications/Adobe_Acrobat_2020_20240514/Acrobat Distiller.app' '%s'", fileName);
		system(scratchString);  // In general, system() can be a serious security risk. If concerned, delete.
	}  // AnyPostProcessing
}  // execute_PostScript_PostProcessing()



// User-changeable function: what should be output? Can matter because output can be very big.
bool exportQ(ExportWhat const exprtWhat,  ExportFormat const exportFormat,  const Tiling * const tlngP,  const unsigned long int numLinesThisFile)
{
	long int const ExcelMaxNumRows = 1048576;  // Maximum number of rows in Excel versions >=2013.

	switch(exportFormat)
	{
	case JSON:
		return( true );

	case PS_data:
		return( tlngP->tilingId == tlngP->numTilings - 1 );

	case SVG_rhomb:
	case SVG_arcs:
		return( tlngP->tilingId >= -1 );  // Null condition, always true

	case PS_arcs:
	case PS_rhomb:
		return( tlngP->tilingId >= -1 );  // Null condition, always true

	case TSV:
		switch(exprtWhat)
		{
		case Anything:
			return( 18 + numLinesThisFile < ExcelMaxNumRows );
		case pathStats:
			return( 10 + numLinesThisFile + tlngP->numPathStats                         < ExcelMaxNumRows );
		case Paths:
			return( 10 + numLinesThisFile + tlngP->numPathsClosed + tlngP->numPathsOpen < ExcelMaxNumRows - 10240 );  // Leaving space for subsequent pathStats
		case Rhombi:
			return( 10 + numLinesThisFile + tlngP->numFats + tlngP->numThins            < ExcelMaxNumRows - 10240 );  // Leaving space for subsequent pathStats
		}  // switch(exprtWhat)
		break;  // Redundant

	}  // switch(exportFormat)

	return false;  // Redundant
}  // exportQ()



// This test was used to make documentation that shows effect of holesFill().
// But in production, want holesFill() always.
bool holesFillQ(const Tiling * const tlngP)
{
	return true; // Example alternative:   return (tlngP->tilingId <= 2);
}  // holesFillQ()



// These can be changed to show, in SVG, only a subset of the rhombi.
// Comments have example, as used to make image in documentation.
// These y values are as generated by C code; SVG's y values are -1* these.
const double svg_toPaint_xMin(const Tiling * const tlngP) {return -999999;}  // -0.09830056, from tilingId==10, paths 13 and 30, + edgeLength * Sin(18)
const double svg_toPaint_yMin(const Tiling * const tlngP) {return -999999;}  // +0.46449333, from tilingId==10, paths 13 and 30, + edgeLength * Sin(36)
const double svg_toPaint_xMax(const Tiling * const tlngP) {return +999999;}  // +1.27553483, from tilingId==10, paths 13 and 30, - edgeLength * Sin(18)
const double svg_toPaint_yMax(const Tiling * const tlngP) {return +999999;}  // +1.62459848, from tilingId==10, paths 13 and 30, - edgeLength * Sin(36)
const double svg_displayWidth(const Tiling * const tlngP) {return 960;}  // GitHub seems to use a 1012px column. This that, less a little wiggle room for margin and padding.
const double svg_strokeWidth(const Tiling * const tlngP) {return tlngP->edgeLength / 16;}


const long int svg_arcs_longestPathToBeColoured(void)
{
	// If enlarging this might need to add more colours to "<style>" in tiling_export_PaintArcsSVG().
	return 215;
}  // svg_arcs_longestPathToBeColoured



XY wantedPostScriptCentre(void)
{
	return (XY){.x=0.202,  .y=0.026};
}  // wantedPostScriptCentre()
double wantedPostScriptAspect(void)
{
	return 1.44;  // Portrait A3, less 8.73mm margins all round: (420 - 2*8.73) / (297 - 2*8.73) ~= 1.44001
}  // wantedPostScriptAspect()

bool rhombus_keep(
	const Tiling * const tlngP,  Physique const physique,
	double const xNorth,  double const yNorth,  double const xSouth,  double const ySouth
)
{
	return true;
	// Example alternative:
	// return xNorth > (-1 * tlngP->edgeLength);
}  // rhombus_keep



// Wrappers
const char * filePath(void)
{
	return filePath_staticConst;
}  // filePath()
